Clothes_Shop/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clothes_Shop.Models;
using Clothes_Shop.Data;
using Microsoft.AspNetCore.Identity;
using Clothes_Shop.Services;

namespace Clothes_Shop.Controllers
{
    
    public class CartsController : Controller
    {
        private readonly CartContext _context;
        private readonly ItemsContext _itemcontext;
        private readonly ApplicationDbContext _context7;

        private readonly ICategoriesRepository _categoryContext;
        private readonly IGendersRepository _gendersContext;
        private readonly IFeaturesRepository _featuresContext;
        private readonly ItemsContext _contextIt;

        UserManager<IdentityUser> userManager;

        public CartsController(CartContext context, ItemsContext Goodcontext, UserManager<IdentityUser> userManager, 
            ApplicationDbContext context7, ICategoriesRepository categoryContext, 
            IGendersRepository gendersContext, IFeaturesRepository featuresContext, ItemsContext contextIt)
        {
            _itemcontext = Goodcontext;
            _context = context;
            _context7 = context7;
            this.userManager = userManager;
            _categoryContext = categoryContext;
            _gendersContext = gendersContext;
            _featuresContext = featuresContext;
            _contextIt = contextIt;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var user = await userManager.GetUserAsync(User);

        
            List<Item> cartProducts = new List<Item>();

            var cart = _context.Cart.Where(c => c.UserId == user.Id).ToListAsync();
            var ite = _itemcontext.Item.ToList();

            List<Item> items = new List<Item>(); 


            foreach (var i in cart.Result)
            {
                foreach (var j in ite)
                {
                    var item7 = _itemcontext.Item.Where(c => c.Id == i.ItemId);
                    //items = _Goodcontext.Item.Where(c => c.Id == i.ItemId).ToList();


                    if (!items.Contains(j) && i.UserId == user.Id && j.Id == i.ItemId)
                    {
                        items.Add(j);
                    }
                    
                }
                    //cartProducts.AddRange(items);
            }

            /*
            var item8 = await _contextIt.Item.FirstOrDefaultAsync(m => m.Id == id);


            var Desc = _featuresContext.AllFeatures.FirstOrDefault(m => m.Id == item8.FeaturesId);


            var Category = _categoryContext.AllCategories.FirstOrDefault(m => m.Id == item8.CategoryId);

            var Gender = _gendersContext.AllGenders.FirstOrDefault(m => m.Id == item8.GenderId);

            ViewBag.Desc = Desc.Description;

            ViewBag.Category = Category;

            ViewBag.Size = Desc.Size;
            ViewBag.Color = Desc.Color;
            ViewBag.Material = Desc.Material;
            ViewBag.Country = Desc.Country;
            ViewBag.Gender = Gender.Name;*/

            cartProducts.AddRange(items);


            //cartProducts.AddRange(items);

            return View(cartProducts);
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        
        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        public async Task<IActionResult> Create(string GoodId)
        {
            var user = await userManager.GetUserAsync(User);
            // var gd = _Goodcontext.Goods.Where(u => u.Good.Id.Equals(GoodId));
            Item good = _itemcontext.Item.Find(GoodId);

            List <Cart> allcarts = _context.Cart.ToList();
            
            foreach (var t in allcarts) {
                if (t.ItemId == GoodId && t.UserId == user.Id) {
                    return NotFound("An item is already in your cart !!!");
                }
            
            }


            Console.WriteLine(good);
            Cart cart = new Cart();
            //var user =  userManager.GetUserAsync(User).Result;
            var varUser = _context7.Users.Where(u => u.Email.Equals(User.Identity.Name));
            //var user = varUser.FirstOrDefault();
           
            //var user = User.Identity.;
            // var good = _goodsRepository.AllGoods.FirstOrDefault(p => p.Id == id);
            if (ModelState.IsValid)
            {
                //    cart.Good = good;
                cart.Id = good.Id + "CART" + user.Id;
                cart.ItemId = good.Id;
                cart.UserId = user.Id;
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound("Id null");
            }

            var cart = await _context.Cart.FirstOrDefaultAsync(m => m.ItemId == id);


            if (cart == null)
            {
                return NotFound("Cart null");
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await userManager.GetUserAsync(User);
            //var cart = await _context.Cart.FindAsync(id);
            
            var cart = _context.Cart.Where(m => m.UserId == user.Id).ToList();
            List<Cart> cart2 = cart;

            var cart3 = cart2.FirstOrDefault(m => m.ItemId == id);
                 
            _context.Cart.Remove(cart3);


            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(string id)
        {
            return _context.Cart.Any(e => e.Id == id);
        }
    }
}

Clothes_Shop/Controllers/GendersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clothes_Shop.Models;
using Clothes_Shop.Data;

namespace Clothes_Shop.Controllers
{
    public class GendersController : Controller
    {
        private readonly GendersContext _context;

        public GendersController(GendersContext context)
        {
            _context = context;
        }

        // GET: Genders
        public async Task<IActionResult> Index()
        {
            return View(await _context.Gender.ToListAsync());
        }

        // GET: Genders/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gender = await _context.Gender
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gender == null)
            {
                return NotFound();
            }

            return View(gender);
        }

        // GET: Genders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Gender gender)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gender);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gender);
        }

        // GET: Genders/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gender = await _context.Gender.FindAsync(id);
            if (gender == null)
            {
                return NotFound();
            }
            return View(gender);
        }

        // POST: Genders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name")] Gender gender)
        {
            if (id != gender.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gender);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenderExists(gender.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gender);
        }

        // GET: Genders/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gender = await _context.Gender
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gender == null)
            {
                return NotFound();
            }

            return View(gender);
        }

        // POST: Genders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var gender = await _context.Gender.FindAsync(id);
            _context.Gender.Remove(gender);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenderExists(string id)
        {
            return _context.Gender.Any(e => e.Id == id);
        }
    }
}

Clothes_Shop/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace FINAL_DOT_NET.Controllers
{
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> roleManager;

        /// 
        /// Injecting Role Manager
        /// 
        /// 
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }






        public async Task<IActionResult> Update(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role != null)
                return View(role);
            else
                return RedirectToAction("Index");
        }




        [HttpPost]
        public async Task<IActionResult> Update(string id, string name)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role != null)
            {
                if (!string.IsNullOrEmpty(name))
                {
                    role.Name = name;
                    //role.UserName = email;
                }
                else
                    ModelState.AddModelError("", "Name cannot be empty");

       

                if (!string.IsNullOrEmpty(name))
                {
                    IdentityResult result = await roleManager.UpdateAsync(role);
                    if (result.Succeeded)
                        return RedirectToAction("Index");

                }
            }
            else
                ModelState.AddModelError("", "Role Not Found");
            return View(role);
        }





        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            await roleManager.DeleteAsync(role);

            return RedirectToAction("Index");

        }
    }
}

Clothes_Shop/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clothes_Shop.Controllers
{
    public class UsersController : Controller
    {
            UserManager<IdentityUser> userManager;

            private IPasswordHasher<IdentityUser> passwordHasher;



            public UsersController(UserManager<IdentityUser> userManager, IPasswordHasher<IdentityUser> passwordHash)
            {
                this.userManager = userManager;
                passwordHasher = passwordHash;
            }

            public IActionResult Index()
            {
                var users = userManager.Users.ToList();
                return View(users);
            }

            public IActionResult Create()
            {
                return View(new IdentityUser());
            }

            public async Task<IActionResult> Update(string id)
            {
                var user = await userManager.FindByIdAsync(id);
                if (user != null)
                    return View(user);
                else
                    return RedirectToAction("Index");
            }








            [HttpPost]
            public async Task<IActionResult> Update(string id, string email, string password)
            {
                var user = await userManager.FindByIdAsync(id);

                if (user != null)
                {
                    if (!string.IsNullOrEmpty(email))
                    {
                        user.Email = email;
                        user.UserName = email;
                    }
                    else
                        ModelState.AddModelError("", "Email cannot be empty");

                    if (!string.IsNullOrEmpty(password))
                        user.PasswordHash = passwordHasher.HashPassword(user, password);
                    else
                        ModelState.AddModelError("", "Password cannot be empty");

                    if (!string.IsNullOrEmpty(email) && !string.IsNullOrEmpty(password))
                    {
                        IdentityResult result = await userManager.UpdateAsync(user);
                        if (result.Succeeded)
                            return RedirectToAction("Index");

                    }
                }
                else
                    ModelState.AddModelError("", "User Not Found");
                return View(user);
            }





            [HttpPost]
            public async Task<IActionResult> Delete(string id)
            {
                var user = await userManager.FindByIdAsync(id);

                await userManager.DeleteAsync(user);

                return RedirectToAction("Index");

            }

            [HttpPost]
            public async Task<IActionResult> Create(IdentityUser user)
            {
                await userManager.CreateAsync(user);
                return RedirectToAction("Index");
            }
        }
}

Clothes_Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClothesShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:#f2f7f3">

    <header style="background-color:white;margin-bottom:20px">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="margin-left:580px;font-size:37px;color:black;font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">ClothesShop</a>
        <hr />
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom">
            <div class="container" style="margin-left:20px;">
                <!---->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Genders" asp-action="Index">Gender</a>
                            </li>

                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Clothes</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Carts" asp-action="Index">Cart</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!--
    <footer class="border-top footer text-muted" style="position:absolute;margin-top:400px;background-color:white">
        <div class="container" style="margin-left:560px;font-size:20px;color:black;font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">
            &copy; 2020 - ClothesShop
        </div>
    </footer>
    -->

    <footer class="text-center text-lg-start" style="clear: both; position: relative;margin-top:400px; bottom:-55px;background-color:lightgray">
        <!-- Grid container -->
        <div class="container p-4">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                    <h5 class="text-uppercase">About Us</h5>

                    <p>
                        Welcome to ClothesShop, your number one source for clothes. We're dedicated to giving you the very best of clothes, with a focus on uniqueness.
                        Founded in 2020 by Ablaihan Bexeit, ClothesShop has come a long way from its beginnings in Almaty.
                    </p>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Privacy Policy</h5>

                    <p>
                        When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device.
                        Additionally, as you browse the Site, we collect information about the individual web pages or products that you view, what websites or search terms referred you to the Site, and information about how you interact with the Site. We refer to this automatically collected information as Device Information.
                       
                    </p>
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            <div class="container" style="font-size:20px;color:black;font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">
                &copy; 2020 - ClothesShop
            </div>
        </div>
        <!-- Copyright -->
    </footer>






    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>