Clothes_Shop/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Clothes_Shop.Models
{
    public class Item
    {
        public Item(string Id, string Name, String CategoryId, String FeaturesId, Features Features, String GenderId, double Price, string Image)
        {
            this.Id = Id;
            this.Name = Name;
            this.CategoryId = CategoryId;
            this.Features = Features;
            this.GenderId = GenderId;
            this.Price = Price;
            this.Image = Image;
            this.FeaturesId = FeaturesId;
        }

        public Item() { }

        [Required]
        public string Id { get; set; }

        [Required]
        public string Name { get; set; }

        
        public string CategoryId { get; set; }

        public String FeaturesId { get; set; }
        public Features Features { get; set; }

        
        public string GenderId { get; set; }

       
        public double Price { get; set; }

        [Required]
        public string Image { get; set; }

    }
}

Clothes_Shop/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clothes_Shop.Models;
using Clothes_Shop.Data;
using Microsoft.AspNetCore.Identity;
using Clothes_Shop.Services;

namespace Clothes_Shop.Controllers
{
    
    public class CartsController : Controller
    {
        private readonly CartContext _context;
        private readonly ItemsContext _itemcontext;
        private readonly ApplicationDbContext _context7;

        private readonly ICategoriesRepository _categoryContext;
        private readonly IGendersRepository _gendersContext;
        private readonly IFeaturesRepository _featuresContext;
        private readonly ItemsContext _contextIt;

        UserManager<IdentityUser> userManager;

        public CartsController(CartContext context, ItemsContext Goodcontext, UserManager<IdentityUser> userManager, 
            ApplicationDbContext context7, ICategoriesRepository categoryContext, 
            IGendersRepository gendersContext, IFeaturesRepository featuresContext, ItemsContext contextIt)
        {
            _itemcontext = Goodcontext;
            _context = context;
            _context7 = context7;
            this.userManager = userManager;
            _categoryContext = categoryContext;
            _gendersContext = gendersContext;
            _featuresContext = featuresContext;
            _contextIt = contextIt;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var user = await userManager.GetUserAsync(User);

        
            List<Item> cartProducts = new List<Item>();

            var cart = _context.Cart.Where(c => c.UserId == user.Id).ToListAsync();
            var ite = _itemcontext.Item.ToList();

            List<Item> items = new List<Item>(); 


            foreach (var i in cart.Result)
            {
                foreach (var j in ite)
                {
                    var item7 = _itemcontext.Item.Where(c => c.Id == i.ItemId);
                    //items = _Goodcontext.Item.Where(c => c.Id == i.ItemId).ToList();


                    if (!items.Contains(j) && i.UserId == user.Id && j.Id == i.ItemId)
                    {
                        items.Add(j);
                    }
                    
                }
                    //cartProducts.AddRange(items);
            }

            /*
            var item8 = await _contextIt.Item.FirstOrDefaultAsync(m => m.Id == id);


            var Desc = _featuresContext.AllFeatures.FirstOrDefault(m => m.Id == item8.FeaturesId);


            var Category = _categoryContext.AllCategories.FirstOrDefault(m => m.Id == item8.CategoryId);

            var Gender = _gendersContext.AllGenders.FirstOrDefault(m => m.Id == item8.GenderId);

            ViewBag.Desc = Desc.Description;

            ViewBag.Category = Category;

            ViewBag.Size = Desc.Size;
            ViewBag.Color = Desc.Color;
            ViewBag.Material = Desc.Material;
            ViewBag.Country = Desc.Country;
            ViewBag.Gender = Gender.Name;*/

            cartProducts.AddRange(items);


            //cartProducts.AddRange(items);

            return View(cartProducts);
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        
        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        public async Task<IActionResult> Create(string GoodId)
        {
            var user = await userManager.GetUserAsync(User);
            // var gd = _Goodcontext.Goods.Where(u => u.Good.Id.Equals(GoodId));
            Item good = _itemcontext.Item.Find(GoodId);

            List <Cart> allcarts = _context.Cart.ToList();
            
            foreach (var t in allcarts) {
                if (t.ItemId == GoodId && t.UserId == user.Id) {
                    return NotFound("An item is already in your cart !!!");
                }
            
            }


            Console.WriteLine(good);
            Cart cart = new Cart();
            //var user =  userManager.GetUserAsync(User).Result;
            var varUser = _context7.Users.Where(u => u.Email.Equals(User.Identity.Name));
            //var user = varUser.FirstOrDefault();
           
            //var user = User.Identity.;
            // var good = _goodsRepository.AllGoods.FirstOrDefault(p => p.Id == id);
            if (ModelState.IsValid)
            {
                //    cart.Good = good;
                cart.Id = good.Id + "CART" + user.Id;
                cart.ItemId = good.Id;
                cart.UserId = user.Id;
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound("Id null");
            }

            var cart = await _context.Cart.FirstOrDefaultAsync(m => m.ItemId == id);


            if (cart == null)
            {
                return NotFound("Cart null");
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await userManager.GetUserAsync(User);
            //var cart = await _context.Cart.FindAsync(id);
            
            var cart = _context.Cart.Where(m => m.UserId == user.Id).ToList();
            List<Cart> cart2 = cart;

            var cart3 = cart2.FirstOrDefault(m => m.ItemId == id);
                 
            _context.Cart.Remove(cart3);


            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartExists(string id)
        {
            return _context.Cart.Any(e => e.Id == id);
        }
    }
}

Clothes_Shop/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clothes_Shop.Data;
using Clothes_Shop.Models;
using Microsoft.AspNetCore.Identity;

namespace Clothes_Shop.Controllers
{
    public class CommentsController : Controller
    {
        private readonly CommentsContext _context;

        UserManager<IdentityUser> userManager;

        public CommentsController(CommentsContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Comments.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Content")] Comments comment)
        {
            var itemId = TempData["itemId"] as string;

            if (ModelState.IsValid)
            {
                DateTime today = DateTime.Now;

                var user = await userManager.GetUserAsync(User);

                comment.Id = user.Id + today.ToString();
                comment.Author = user.Id;
                comment.ItemId = itemId;

                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Items", new { id = itemId });
            }
            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Content")] Comments comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var itemId = TempData["itemId"] as string;
            var comment = await _context.Comments.FindAsync(id);
            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Items", new { id = itemId });
        }

        private bool CommentExists(string id)
        {
            return _context.Comments.Any(e => e.Id == id);
        }
    }
}

Clothes_Shop/Views/Items/Create.cshtml
@model Clothes_Shop.Models.Item




@{
    ViewData["Title"] = "Create";


}


<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label name="Category">Category</label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Category"></select>
            </div>

            <div class="form-group">
                <label name="Gender">Gender</label>
                <select asp-for="GenderId" class="form-control" asp-items="ViewBag.Gender"></select>
            </div>


            <div class="form-group">
                <label asp-for="Features.Size" class="control-label"></label>
                <select asp-for="Features.Size" id="Features.Size" name="Features.Size" class="form-control">
                    <option value="XS">XS</option>
                    <option value="S">S</option>
                    <option value="M">M</option>
                    <option value="L">L</option>
                    <option value="XL">XL</option>
                    <option value="XXL">XXL</option>
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Features.Color" class="control-label"></label>
                <select asp-for="Features.Color" id="Features.Color" name="Features.Color" class="form-control">
                    <option style="background-color:white" value="White">White</option>
                    <option style="background-color:green" value="Green">Green</option>
                    <option style="background-color:black" value="Black">Black</option>
                    <option style="background-color:yellow" value="Yellow">Yellow</option>
                    <option style="background-color:blue" value="Blue">Blue</option>
                    <option style="background-color:red" value="Red">Red</option>
                </select>
            </div>


            <div class="form-group">
                <label asp-for="Features.Description" class="control-label"></label>
                <input asp-for="Features.Description" class="form-control" />
                <span asp-validation-for="Features.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Features.Material" class="control-label"></label>
                <input asp-for="Features.Material" class="form-control" />
                <span asp-validation-for="Features.Material" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Features.Country" class="control-label"></label>
                <input asp-for="Features.Country" class="form-control" />
                <span asp-validation-for="Features.Country" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<!--
    section scripts{
        <script type="text/javascript">

            // Add the following code if you want the name of the file appear on select
            $(".custom-file-input").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
        </script>
    }
    -->

Clothes_Shop/Views/Items/Delete.cshtml
@model Clothes_Shop.Models.Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Clothes_Shop/Views/Items/Details.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

@model Clothes_Shop.Models.Item

@{
    ViewData["Title"] = "Details";
    var Lst = ViewBag.Comments as IEnumerable<Clothes_Shop.Models.Comments>;
    var Usr = ViewBag.Allusers as IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>;

    
}









<div class="container">



    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <!--  <img style="width: 459px" th:src="{'/images/'+${}}" /> -->
                        <img class="product__image" src="~/images/@Model.Image" style="width: 359px; height: 500px; margin-top:50px;margin-left:40px " />
                    </div>

                </article> <!-- gallery-wrap .end// -->
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mb-3"> @Html.DisplayFor(model => model.Name)</h3>

                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">US $</span><span class="num">  @Html.DisplayFor(model => model.Price)</span>
                        </span>
                    </p> <!-- price-detail-wrap .// -->
                    <dl class="item-property">
                        <dt>Description</dt>
                        <dd><p> @ViewBag.Desc </p></dd>
                    </dl>               
                    <dl class="item-property">
                        <dt>Size</dt>
                        <dd><p> @ViewBag.Size </p></dd>
                    </dl>
                    <dl class="item-property">
                        <dt>Color</dt>
                        <dd><p> @ViewBag.Color </p></dd>
                    </dl>
                    <dl class="item-property">
                        <dt>Material</dt>
                        <dd><p> @ViewBag.Material </p></dd>
                    </dl>
                    <dl class="item-property">
                        <dt>Gender</dt>
                        <dd><p> @ViewBag.Gender </p></dd>
                    </dl>
                    <dl class="item-property">
                        <dt>Manufacturer</dt>
                        <dd><p> @ViewBag.Country </p></dd>
                    </dl>


                    <dl class="param param-feature">
                        <dt>Delivery</dt>
                        <dd>Russia, USA, and Europe</dd>
                    </dl>

                    <div style="margin-top: 60px">
                        <a asp-action="Index" class="btn btn-lg btn-outline-primary text-uppercase">Back to List</a>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-lg btn-outline-primary text-uppercase">Edit</a>

                        }
                        <a asp-controller="Carts" asp-action="Create" asp-route-GoodId="@Model.Id" class="btn btn-lg btn-outline-primary text-uppercase">Add to cart</a>
                    </div>
                </article> <!-- card-body.// -->
            </aside> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
</div>



<h4 style="margin-top:50px;margin-left:500px">Comments</h4>
<hr />



<div class="row" style="margin-left:30px;margin-top:5px">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Comments" method="post">
            <div class="text-danger"></div>

            <h5>Post a comment</h5>

            <div class="form-group">
                <label name="Content" class="control-label"></label>
                <input name="Content" class="form-control" />
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


    <ul class="comment-section" style="margin-bottom:200px">

        @foreach (var j in Lst)
        {
            @foreach (var i in Usr)
            {
                if (j.Author == i.Id)
                {

            <div style="border:solid;border-color:lightgray;border-width:1px" class="container">


                <div class="row" style="margin-left:5px;margin-top:5px">

                    <img src="~/images/human.png" style="width:60px;margin-top:10px;height:60px" />
                    <div class="col-sm">
                        <p style="font-size:20px;font-weight:bold">@i.Email</p>

                        <p style="font-size:17px;">@j.Content</p>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a asp-controller="Comments" asp-action="Delete" asp-route-id="@j.Id">Delete</a>

                        }
                    </div>
                </div>

            </div>
                 <br>
                    <!-- <li>i.Emailj.Content</li>-->
                }
            }
        }

</ul>
    <!--<td>Lst.FirstOrDefault().Content </td> -->

Clothes_Shop/Views/Items/Index.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

@model IEnumerable<Clothes_Shop.Models.Item>
<!--model IEnumerable<FINAL_DOT_NET.ViewModels.GoodsViewModel>-->
@{
    ViewData["Title"] = "Index";
    
}




<h1 style="text-align:center">Clothes</h1>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p style="text-align:center">
        <a asp-action="Create">Create New</a>
    </p>
}




<div class="row" style="margin-top:50px">

    <div class="column">
        <form asp-action="Search" style="margin-bottom:-40px">

            <div class="row">
                <input name="text" type="text" class="form-control" style="width:300px;margin-left:760px" />
                <input type="submit" value="Search" class="btn btn-primary" style="margin-left:5px" />
            </div>

        </form>
    </div>



    <div class="column">
        <form asp-action="Filter" style="margin-left:400px;margin-top:-23px">

            <div class="row">
                <div class="form-group">
                    <label name="CategoryId"></label>
                    <select name="CategoryId" class="form-control" asp-items="@ViewBag.Category"></select>
                </div>

                <div class="form-group">
                    <label name="GenderId"></label>
                    <select name="GenderId" class="form-control" asp-items="@ViewBag.Gender"></select>
                </div>

                <div class="form-group">
                    <label name="SizeId" class="control-label"></label>
                    <select name="SizeId" id="SizeId" class="form-control">
                        <option value="XS">XS</option>
                        <option value="S">S</option>
                        <option value="M">M</option>
                        <option value="L">L</option>
                        <option value="XL">XL</option>
                        <option value="XXL">XXL</option>
                    </select>
                </div>

                <div class="form-group">
                    <input type="submit" value="Filter" class="btn btn-primary" style="margin-left:5px;margin-top:24px" />
                </div>

            </div>

        </form>
    </div>
    </div>


    <style>

        .card-product:after {
            content: "";
            display: table;
            clear: both;
            visibility: hidden;
        }

        .card-product .price-new, .card-product .price {
            margin-right: 5px;
        }

        .card-product .price-old {
            color: #999;
        }

        .card-product .img-wrap {
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }

            .card-product .img-wrap img {
                max-height: 100%;
                max-width: 100%;
                object-fit: cover;
            }

        .card-product .info-wrap {
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .action-wrap {
            padding-top: 4px;
            margin-top: 4px;
        }

        .card-product .bottom-wrap {
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .title {
            margin-top: 0;
        }
    </style>



    <div class="container" style="margin-left: 55px;margin-top: 70px;margin-bottom: 100px">

        <div class="row">



            @foreach (var item in Model)
            {
                <a asp-action="Details" asp-route-id="@item.Id" style="cursor: pointer;">
                    <div>
                        <figure class="card card-product" style="width: 220px;margin-left: 30px">
                            <div class="img-wrap">
                                <img class="product__image" src="~/images/@item.Image" />


                            </div>


                            <figcaption class="info-wrap">
                                <h6 class="title text-dots">
                                    <a asp-action="Details" asp-route-id="@item.Id">
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </a>

                                </h6>
                                <h7>
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a asp-action="Edit" asp-route-id="@item.Id">Edit |</a>
                                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    }
                                </h7>

                                <div class="action-wrap">
                                    <a asp-controller="Carts" asp-action="Create" asp-route-GoodId="@item.Id" class="btn btn-primary btn-sm float-right">Add to cart</a>



                                    <div class="price-wrap h5">
                                        US $ @Html.DisplayFor(modelItem => item.Price)
                                    </div> <!-- price-wrap.// -->
                                </div> <!-- action-wrap -->
                            </figcaption>
                        </figure> <!-- card // -->

                    </div>
                </a>
            }



        </div>

    </div>